const express=require('express')
const app=express()
const secPage=require('./secPage.js')
const user=require('./user.js')
const services=require('./services.js')
const HomePage=require('./HomePage.js')
const about=require('./about.js')
const contact=require('./contact.js')
app.get('/',(request,response) =>{
    
   response.send("Get Router on Home Page")
})
app.use('/secPage',secPage)
app.use('/user',user)
app.use('/services',services)
app.use('/HomePage',HomePage)
app.use('/about',about)
app.use('/contact',contact)
app.listen(3800)